// fildariane.js

function loadfildariane(){
	var url = document.location.href;
	if (url == document.location.href){
		var fildariane = url.replace("//", ">")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
		var fildariane = fildariane.replace("//", " > ")
		var fildariane = fildariane.replace("/", " > ")
		var fildariane = fildariane.replace("_", " ")
	}
	
	var elementinpage = document.getElementById("fildariane");
	elementinpage.innerText = fildariane;
}

loadfildariane();